# Generated by Django 5.1.3 on 2024-11-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiderRegistrationModel',
            fields=[
                ('rider_id', models.AutoField(primary_key=True, serialize=False)),
                ('rider_name', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10)),
                ('student_id', models.CharField(max_length=255)),
                ('university_name', models.CharField(max_length=255)),
                ('drivers_license_id', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('zipcode', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
