# Generated by Django 5.1.4 on 2024-12-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiderRegistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderregistrationmodel',
            old_name='rider_id',
            new_name='id',
        ),
    ]
