# Generated by Django 5.1.3 on 2024-11-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='confirm_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
