# Generated by Django 5.1.4 on 2024-12-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliableRidersLogs',
            fields=[
                ('avaliableriders_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('avaliableriders_details', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AvaliableRidersModel',
            fields=[
                ('avaliableriderslist_id', models.AutoField(primary_key=True, serialize=False)),
                ('riders_details', models.JSONField(default={})),
                ('user_id', models.CharField(max_length=255)),
                ('pickup_address', models.TextField()),
                ('pickup_zipcode', models.CharField(max_length=255)),
                ('destination', models.TextField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingLogs',
            fields=[
                ('Booking_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=255)),
                ('booking_details', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RideBookingModel',
            fields=[
                ('Booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('rider_id', models.CharField(max_length=255)),
                ('pickup_address', models.TextField()),
                ('pickup_zipcode', models.CharField(max_length=255)),
                ('destination', models.TextField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_ride_completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
