# Generated by Django 5.1.3 on 2024-11-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideBookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('rider_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('pickup_address', models.TextField()),
                ('pickup_zipcode', models.CharField(max_length=255)),
                ('destination', models.TextField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
