# Generated by Django 5.1.3 on 2024-12-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridebookings',
            name='rider_id',
        ),
        migrations.AddField(
            model_name='ridebookings',
            name='riders_details',
            field=models.JSONField(default={}),
        ),
    ]
