# Generated by Django 5.1.3 on 2024-12-04 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0002_remove_ridebookings_rider_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RideBookings',
            new_name='AvaliableRidersModel',
        ),
        migrations.RenameField(
            model_name='avaliableridersmodel',
            old_name='booking_id',
            new_name='avaliableriderslist_id',
        ),
    ]
