# Generated by Django 5.1.3 on 2024-12-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0003_rename_ridebookings_avaliableridersmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideBookingModel',
            fields=[
                ('Booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('rider_id', models.CharField(max_length=255)),
                ('pickup_address', models.TextField()),
                ('pickup_zipcode', models.CharField(max_length=255)),
                ('destination', models.TextField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
