# Generated by Django 5.1.3 on 2024-12-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0004_ridebookingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLogs',
            fields=[
                ('Booking_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=255)),
                ('booking_details', models.JSONField()),
            ],
        ),
    ]
