# Generated by Django 5.1.3 on 2024-12-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0005_bookinglogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliableRidersLogs',
            fields=[
                ('avaliableriders_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('avaliableriders_details', models.JSONField()),
            ],
        ),
    ]
