# Generated by Django 5.1.3 on 2024-12-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0006_avaliableriderslogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebookingmodel',
            name='is_ride_completed',
            field=models.BooleanField(default=False),
        ),
    ]
