# Generated by Django 5.1.3 on 2024-12-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0007_ridebookingmodel_is_ride_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridebookingmodel',
            name='is_ride_completed',
            field=models.BooleanField(default=True),
        ),
    ]
