# Generated by Django 5.1.4 on 2024-12-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiderOTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rider_id', models.CharField(max_length=255)),
                ('otp', models.CharField(max_length=255)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
